services:
  rocky9base:
    build:
      context: .
      secrets:
        - forge_key
      args:
        rocky: $RL9
        platform: puppet8
        DNF_ENV_FILE: /run/secrets/forge_key
  rocky9docs:
    build:
      context: .
      dockerfile: Dockerfile.strings
      args:
        rocky: $RL9

secrets:
  forge_key:
    file: secrets/forge-key.sh
